# Generated by Django 5.0.6 on 2024-06-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegisterForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("job_position", models.CharField(max_length=50)),
                ("bussines_area", models.CharField(max_length=50)),
                ("self_description", models.TextField(max_length=200)),
                ("job_expectation", models.TextField(max_length=200)),
                ("programming_lang", models.CharField(max_length=50)),
                ("lang_frameworks", models.CharField(max_length=50)),
                ("last_framework", models.CharField(max_length=50)),
                ("last_post_experience", models.CharField(max_length=50)),
                ("last_comp_name", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("phone_code", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
            ],
        ),
    ]
