# Generated by Django 5.0.6 on 2024-06-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RegisterForm",
            new_name="Register",
        ),
    ]
