# Generated by Django 5.0.6 on 2024-06-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_register_bussines_area_alter_register_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="lang_frameworks",
        ),
    ]
